---
abstract: 'Fast, simple message transformations'
author:
  - 'Dana M. Diederich <diederich@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Message-Transform
provides:
  Message::Transform:
    file: lib/Message/Transform.pm
    version: 0.2
requires:
resources:
  license: http://dev.perl.org/licenses/
version: 0.2
